name: sleap

dependencies:
- python=3.7
- sleap::tensorflow=2.7.0
- sleap::pyside2=5.14.1
- Pillow
- Shapely
- wheel=0.32.0
- conda-build=3.21.7
- anaconda-client
- conda-verify
- pip
- pip:
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"