name: sleap_ci

channels:
    - conda-forge
    - anaconda

dependencies:
    # Needed for the build
    - conda-build
    - anaconda-client
    - conda-verify
    - twine
    - pip
    - pip:
        - build
