main:

  - name: fps
    label: Frames Per Second
    type: int
    range: 1,200
    default: 30
  - name: crop
    label: Crop Size
    type: list
    options: None,Half,Quarter
  - name: scale
    label: Output Scale
    type: double
    default: 1.0
    range: 0.1,1.0
  - name: use_gui_visuals
    label: Use GUI Visual Settings (colors, line widths)
    type: bool
    default: true
  - name: open_when_done
    label: Open When Done Saving
    type: bool
    default: true
