add instance: Ctrl+I
add videos: 
clear selection: Esc
close: Ctrl+Q
color predicted: 
delete area: Ctrl+K
delete clip:
delete instance: Ctrl+Backspace
delete track: Ctrl+Shift+Backspace
export clip:
fit: Ctrl+=
goto frame: Ctrl+J
goto marked: Ctrl+Shift+M
goto last interacted: Ctrl+A
goto next suggestion: Space
goto next track spawn: Ctrl+E
goto next user: Ctrl+U
goto next labeled: Alt+Right
goto prev suggestion: Shift+Space
goto prev labeled: Alt+Left
learning: Ctrl+L
mark frame: Ctrl+M
new: Ctrl+N
next video: Alt+Shift+Right
open: Ctrl+O
prev video: Alt+Shift+Left
save as: Ctrl+Shift+S
save: Ctrl+S
select next: '`'
select to frame: Ctrl+Shift+J
show instances: H
show edges: Ctrl+Shift+Tab
show labels: Ctrl+Tab
show trails: 
transpose: Ctrl+T
frame next: Right
frame prev: Left
frame next medium step: Ctrl+Right
frame prev medium step: Ctrl+Left
frame next large step: Ctrl+Alt+Right
frame prev large step: Ctrl+Alt+Left
